#CLASS NOTES 2/16 - guessing game

#Let's say we have a guessing game
#We will have a human player that will guess a number between a range of 1 to n (user specified)
#the program will tell the user if the number they guess is too large, is smaller, or is equal to the secret #
#the program will randomly generate the number the user is guessing
#if the player wants to give up, then the player can enter a 0 or a negative number
#we will need to import random
#you are also told that your program will need to check if the number guessed by the user makes sense
#which means that the number falls between the upper and lower bounds
#--- the highest number that can be guessed and the lowest number that can be guessed
#we are also going to assume that the user only has five tries to guess the random number

import random

print('Welcome to our Guessing Game! Please guess a number between the range of 1 to n, '
      'where you will specify n.')
print('After inputting the range, next you will enter your guess. if you want to stop playing '
      'enter a 0 or a negative number.')

#first we will have the user select the number that will be the upper bound or the
# stopping range condition (highest number it could be)

upper_bound = int(input('Please enter the largest number that you would like as the end '
                        'of the games number range: '))
#create a lower bound variable -- which just means the starting condition of range -- lowest number that could be a
#viable guess
lower_bound = 1

#let's think about what else we need here
    #a variable to hold the user's guess
    #a variable to keep count of the number of the user's guesses
    #a count variable for our loop -- its going to be a while loop

#need to generate a random number -- using random.randint() -- generates a random number
    #example - random.randint(1,9) -- this will return a random number from [1,2,3,4,5,6,7,8,9]
    #for i in range(9) would be 1 - 8 (REMEMBER - computer starts counting at 0)

#create a variable to hold the number to be guessed
to_be_guessed = random.randint(lower_bound,upper_bound)

users_actual_guess = 0

#we know that we only have five guesses so we are creating the count variable
count = 1

#using a while loop   (!= -- not equal to)
#here our while loop will run as long as the nuber guessed by the user is not the actual number generated by the
#program as the number to be guessed and as long as they have not guessed more than 5 times

#(1) - check that the user's actual guess is within the range
#(2) display messages if
    #too large
    #too small
    #guess correctly

#BOOLEAN COMPARISON OPERATORS:
#and, not, or
#TWO EXPRESSIONS THAT YIELD A TYPE BOOL (BOOLEAN) CAN BE COMBINED WITH THE BOOLEAN COMPARISON OPERATORS
#example:       using the AND
#a = 1
#if a > 0 and a <= 100:
    #print('Great Job!')
while users_actual_guess != to_be_guessed and count <= 5:
    users_actual_guess = int(input('Please enter a new number for your guess of what the random number is: '))
    if users_actual_guess == 0 or users_actual_guess <= 0:
        print('Sorry that you have chosen to quit the game!')
        break
    elif users_actual_guess > upper_bound:
        print('Sorry! Your guess is not within the specified boundaries!')
    elif users_actual_guess < to_be_guessed:
        print('Sorry, your guess is too small!')
    elif users_actual_guess > to_be_guessed:
        print('Sorry, your guess is too large!')
    else:
        print('Congrats! You guessed the right number!!')
    #we need to increase our count variable
    count += 1

print('Thanks for playing!')












